sudo: required
services:
  - docker

before_install:
  - docker build -t iwinokurow/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true iwinokurow/react-test npm test
  
after_success:
  - docker build -t iwinokurow/multi-client ./client
  - docker build -t iwinokurow/multi-nginx ./nginx
  - docker build -t iwinokurow/multi-server ./server
  - docker build -t iwinokurow/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push iwinokurow/multi-client
  - docker push iwinokurow/multi-nginx
  - docker push iwinokurow/multi-server
  - docker push iwinokurow/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-571169730856
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
